name: Build artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Generate build files
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build project
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3

      - name: Doxygen Action
        # You may pin to the exact commit or the version.
        # uses: mattnotmitt/doxygen-action@cbe72c8e402e8a3faa1f0b247ef90aa6c8e4ce74
        uses: mattnotmitt/doxygen-action@1.9.8
        with:
          # Working directory
          working-directory: ./docs
